---

- include_tasks: yarn.yml

- name: Add backports repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.filename }}"
  with_items:
    - {repo: "deb http://ftp.debian.org/debian stretch-backports main", filename: backports}

- name: Install nodejs
  apt:
    name: nodejs
    state: latest
    default_release: stretch-backports

- name: Install requirements
  apt:
    pkg:
      - curl
      - gnupg
      - debian-archive-keyring
      - apt-transport-https
      - ca-certificates
      - git
      - yarn
      - make
      - unzip
    state: latest

- name: Download
  git:
    repo: "{{ shaarli_git_url }}"
    version: "{{ shaarli_version }}"
    dest: /opt/shaarli
    force: yes
  register: shaarli_download
  notify: restart php

- name: Install dependencies
  composer:
    command: install
    working_dir: /opt/shaarli
    prefer_dist: True
    no_dev: False
    optimize_autoloader: True

- name: Build frontend
  command: "make build_frontend"
  args:
    chdir: /opt/shaarli
  when: shaarli_download is changed

- name: Configure
  template:
    owner: shaarli
    group: shaarli
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - opt/shaarli/data/config.json.php
    - opt/shaarli/data/updates.txt
  notify: restart php

- name: Set permission
  file:
    state: directory
    mode: 0755
    owner: shaarli
    path: "{{ item }}"
  with_items:
    - /opt/shaarli/cache
    - /opt/shaarli/data
    - /opt/shaarli/pagecache
    - /opt/shaarli/tmp

- name: Custom css
  copy:
    src: "{{ shaarli_custom_css }}"
    dest: /opt/shaarli/data/user.css
    owner: shaarli
  when: shaarli_custom_css is defined

- name: Fetch datastore
  fetch:
    src: /opt/shaarli/data/datastore.php
    dest: "{{ shaarli_local_datastore }}"
    flat: yes
  when: shaarli_backup | bool

- name: Upload local datastore
  copy:
    src: "{{ shaarli_local_datastore }}"
    dest: /opt/shaarli/data/datastore.php
    owner: shaarli
    group: shaarli
    mode: 0644
    backup: True
  when: shaarli_restore | bool
